In [3]:
import ast
import pandas as pd
import numpy as np

In [4]:
df_chemdist = pd.read_csv("ido&tdo_ChemDist.csv")
df_chemdist

,Unnamed: 0,CHEMBLID,smiles,ido_ic50,tdo_ic50,embed
0,0,CHEMBL1098875,O=C1c2cc(F)ccc2-n2c1nc1ccccc1c2=O,23.0,60.0,[-14.003065 -23.058441 46.13716 -7.52641...
1,1,CHEMBL1209728,Cc1c(Br)oc2c1C(=O)C(=O)c1c-2ccc2c1CCCC2(C)C,10000.0,10000.0,[ -8.993788 -30.84298 37.763935 -12.15...
2,2,CHEMBL1276265,O=C1c2ccc(Cl)cc2-n2c1nc1ccccc1c2=O,183.0,224200.0,[-13.749965 -23.094172 46.29172 -7.66631...
3,3,CHEMBL1346056,Oc1ccccc1-c1nc2c3ccccc3c3ccccc3c2[nH]1,11790.0,12250.0,[-14.3434515 -20.237873 46.55186 -10.75...
4,4,CHEMBL139935,O=[N+]([O-])c1cc(F)c2cccnc2c1O,14610.0,30230.0,[-14.600085 -24.964235 47.840824 -9.83812...
...,...,...,...,...,...,...
755,755,CHEMBL5221020,O[C@@H]1CCCC[C@H]1CNc1c(Br)ccc2[nH]ncc12,1230.0,11240.0,[ -6.6100674 -35.240223 37.34721 -13.40...
756,756,CHEMBL5221102,Brc1cc(NC[C@H]2CCCN2)c2cn[nH]c2c1,56450.0,7450.0,[-10.37818 -32.02663 39.73027 -14.18832...
757,757,CHEMBL578036,CC1(C)CCCc2c1ccc1c2C(=O)C(=O)c2c(CO)coc2-1,10000.0,450.0,[ -9.41469 -32.008568 38.02041 -12.88767...
758,758,CHEMBL584991,Nc1nonc1/C(=N/O)Nc1ccc(F)c(Cl)c1,50.0,10000.0,[-14.0334 -24.151228 44.50949 -13.63094...
759,759,CHEMBL72165,O=C1c2cc(Br)ccc2-n2c1nc1ccccc1c2=O,53.9,53.0,[-13.990807 -23.040163 45.888317 -7.26684...

In [5]:
df_chemdist2 = pd.DataFrame(np.zeros((760,16)))
df_chemdist2

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
756,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
757,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
758,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
759,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
n = 0
for i in df_chemdist["embed"]:
    data = str(i)    
    list_version = [float(num) for num in data.strip("[]").split()]
    df_chemdist2.iloc[n] = pd.Series(list_version)
    n  = n+1

In [8]:
df_chemdist2

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,-14.003065,-23.058441,46.137160,-7.526415,-14.680629,-2.025073,-2.668684,-4.798969,16.956556,28.177288,15.778368,-7.974331,4.787653,-21.960740,3.326011,-9.688106
1,-8.993788,-30.842980,37.763935,-12.150796,-4.559561,3.368797,-16.726458,-0.450463,19.561825,22.228985,12.471409,-5.286638,14.282381,-17.962238,0.858942,-2.176952
2,-13.749965,-23.094172,46.291720,-7.666314,-14.803009,-1.674854,-2.428345,-4.950026,17.406736,28.317436,15.914805,-8.123228,4.782705,-22.040120,3.003066,-9.793180
3,-14.343452,-20.237873,46.551860,-10.752590,-14.618931,-0.115160,-1.749531,-9.018958,15.462461,29.991219,15.747241,-7.880230,3.059953,-19.909452,2.336827,-10.616964
4,-14.600085,-24.964235,47.840824,-9.838120,-15.556587,-2.510412,-6.130763,-6.216830,17.894226,29.233135,18.129982,-9.611552,4.620627,-22.341133,4.051117,-10.847528
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755,-6.610067,-35.240223,37.347210,-13.406092,-0.086639,4.950376,-19.595678,-1.106861,22.324460,20.796188,9.676053,-6.745124,19.218573,-20.109446,-0.283282,-3.565793
756,-10.378180,-32.026630,39.730270,-14.188325,-2.722742,2.572641,-18.544514,-3.594114,18.125656,23.397170,11.112873,-6.274046,15.503289,-18.983067,2.022580,-4.658357
757,-9.414690,-32.008568,38.020410,-12.887679,-4.310641,2.123005,-19.301645,-0.908163,19.287104,22.181587,13.006796,-6.244154,14.596760,-18.429844,2.206953,-3.002437
758,-14.033400,-24.151228,44.509490,-13.630947,-13.172363,-5.050177,-13.606611,-10.461112,14.584917,28.205460,18.197668,-12.246285,3.934439,-20.749884,8.149105,-13.534802
759,-13.990807,-23.040163,45.888317,-7.266840,-14.698127,-2.185727,-2.705161,-4.473226,16.865458,27.957777,15.767321,-7.879742,4.768635,-21.911133,3.425968,-9.508499

In [9]:
df_chemdist2.to_csv("ido_tdo_chemdist_dataset.csv")