In [1]:
import ast
import pandas as pd
import numpy as np

In [2]:
df_chemdist = pd.read_csv("testdata_ChemDist.csv")
df_chemdist

,Unnamed: 0,CHEMBLID,smiles,ido_ic50,tdo_ic50,embed
0,0,1a,O=S(C(N1)=CC2=C1C=CC=C2)CC3=CC=C(C(F)(F)F)C=C3,5.000000,5.000000,[-14.30475 -22.183504 45.260883 -8.20738...
1,1,1b,O=S(C1=CC2=CC=CC=C2O1)CC3=CC=C(C(F)(F)F)C=C3,5.000000,5.000000,[-13.224975 -21.435287 43.9375 -8.34363...
2,2,1c,O=S(C1=NC2=CC=CC=C2N1)CC3=CC=C(C(F)(F)F)C=C3,5.000000,5.000000,[-14.064718 -21.573818 44.60546 -8.65385...
3,3,1d,O=S(C1=NC2=CC=CC=C2O1)CC3=CC=C(C(F)(F)F)C=C3,5.552842,5.000000,[-13.316064 -20.975462 43.57268 -8.80987...
4,4,1e,O=S(C1=NC2=CC=C(Cl)C=C2O1)CC3=CC=CC=C3C(F)(F)F,5.040959,5.075721,[-13.365523 -20.631634 43.400875 -9.36604...
...,...,...,...,...,...,...
106,106,43a,CS(=O)(NC1=CC=C(C2=CC3=C(C=N2)C(O)=C(OC)C=C3)C...,5.906578,6.698970,[-15.173681 -25.243649 48.170116 -8.66928...
107,107,43b,O=S(C(F)(F)F)(NC1=CC=C(C2=CC3=C(C=N2)C(O)=C(OC...,6.508638,7.096910,[-15.094669 -25.18327 48.048767 -8.84989...
108,108,43c,O=S(C1CC1)(NC2=CC=C(C3=CC4=C(C=N3)C(O)=C(OC)C=...,5.342944,5.473661,[-13.4903345 -26.192087 45.268368 -9.69...
109,109,43d,O=S(N1CCCCC1)(NC2=CC=C(C3=CC4=C(C=N3)C(O)=C(OC...,4.813326,5.098542,[ -9.911153 -31.256895 42.305424 -10.24...
110,110,46,O=C(NC1=CC=CC=C1)NC2=CC=C(C3=CC4=C(C=N3)C(O)=C...,4.296795,4.844968,[-15.897995 -26.544495 49.374493 -9.39069...

In [3]:
df_chemdist2 = pd.DataFrame(np.zeros((111,16)))
df_chemdist2

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
107,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
108,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
109,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
110,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
n = 0
for i in df_chemdist["embed"]:
    data = str(i)    
    list_version = [float(num) for num in data.strip("[]").split()]
    df_chemdist2.iloc[n] = pd.Series(list_version)
    n  = n+1

In [5]:
df_chemdist2

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,-14.304750,-22.183504,45.260883,-8.207386,-13.269386,-3.784027,-3.708170,-7.274212,14.817107,27.683323,14.326466,-9.258812,4.648454,-22.255764,5.140204,-12.161007
1,-13.224975,-21.435287,43.937500,-8.343637,-13.690961,-3.874763,-4.319111,-7.425592,15.142795,27.200592,15.057549,-9.963741,3.844644,-21.782757,5.497138,-12.331086
2,-14.064718,-21.573818,44.605460,-8.653851,-12.546973,-3.923433,-3.966902,-8.295200,14.125566,27.482927,13.651967,-9.568536,4.618308,-22.050745,5.504343,-12.836102
3,-13.316064,-20.975462,43.572680,-8.809876,-13.097700,-3.944204,-4.591758,-8.209767,14.384265,27.149930,14.522554,-9.972846,3.832650,-21.477577,5.748692,-12.663094
4,-13.365523,-20.631634,43.400875,-9.366049,-13.026165,-3.727391,-4.900855,-8.709756,14.058483,27.276781,14.614197,-9.909361,3.598743,-20.994667,5.718984,-12.625678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,-15.173681,-25.243649,48.170116,-8.669281,-14.977760,-2.018267,-4.513259,-4.730712,17.647490,29.083988,16.887707,-8.078361,5.528525,-22.477743,3.215860,-9.501397
107,-15.094669,-25.183270,48.048767,-8.849890,-15.009170,-1.876412,-4.634313,-4.813497,17.700985,29.060747,17.015797,-8.094252,5.449812,-22.304567,3.112107,-9.442337
108,-13.490334,-26.192087,45.268368,-9.699895,-12.185628,0.109706,-7.007256,-3.693572,18.101711,27.351084,15.533730,-6.856073,7.719094,-20.781174,1.958964,-7.133166
109,-9.911153,-31.256895,42.305424,-10.246302,-5.991225,2.720105,-11.111414,-1.746306,21.182755,24.202831,11.590318,-6.765760,14.344964,-21.891376,0.182636,-5.760461
110,-15.897995,-26.544495,49.374493,-9.390694,-14.490724,-2.130945,-5.688927,-5.057926,17.661960,29.649652,16.811066,-8.133999,6.397219,-22.962585,3.428657,-9.712506

In [6]:
df_chemdist2.to_csv("testdata_chemdist_dataset.csv")